[general]
live_config_reload = true
import = [ "~/.config/alacritty/colorschemes/kbtw-ui.toml" ]

[cursor]
style = "Beam"

[env]
term = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.5

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_padding = true
opacity = 1

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 18
y = 18
